name: Alert test
on: 
  pull_request:
    types: [opened, closed]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord
      uses: ViniciusSantos31/github-alert-discord@v1.1.18
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}