name: Alert test
on: 
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: New PR
      uses: ViniciusSantos31/github-alert-discord@v1.1.1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        username: GitHub PR
        avatar_url: https://avatars.githubusercontent.com/u/41171735?v=4